### ISSUE TITLE
internal network error code 40333

### ISSUE THREAD

**Issue by sineckers** [germanoeich/nirn-proxy#14]
I was using nirn for a few weeks until today my bot went offline then i realized nirn gives `internal network error code 40333` on many endpoints with 403. There is no cloudflare ban, ratelimit etc. I changed the api endpoint to discord and everything back to normal. Also tried to run another nirn instance on different vm with different public ip but it gives same error. Any workarounds about this? @germanoeich

**Comment by AwesomeStickz** [comment]
This was an issue on Discord's end and they've fixed it, you shouldn't be getting this error now

**Comment by sineckers** [comment]
yes it seems good now thx
