### ISSUE TITLE
Nirn returns 401 sometimes on interactions

### ISSUE THREAD

**Issue by hydrox19** [germanoeich/nirn-proxy#3]
Hello,

I have been using nirn for the past few months and I have noticed an issue this doesn't seem to happen most of the time but it exists at that particular time when you try to use slash commands it doesn't work anymore. It fails it returns 401 code on my bot. I don't know on which side it failed nirn or discord. I hope you would know anything regarding this.

Client: Discord.js v13
Nirn: 1.1.2

Thank you

**Comment by hydrox19** [comment]
![image](https://user-images.githubusercontent.com/85543339/163232196-d21da7ef-a534-4ac9-91d7-c130c861c14f.png)
I don't think this is fixed

**Comment by hydrox19** [comment]
@germanoeich

**Comment by germanoeich** [comment]
@hydrox19 Hey, what version are you running?

401s are only returned by the proxy when the proxy itself receives a 401 from discord. Did you try with the `DISABLE_401_LOCK` flag set to `true`? Did that help?

It's also wierd that your 429 curve is so high on /gateway/bot, are you spamming that endpoint with multiple bots? Are all your workloads going through the proxy? How many bots or applications that communicate with Discord share the same IP?

**Comment by hydrox19** [comment]
> @hydrox19 Hey, what version are you running?
> 
> 401s are only returned by the proxy when the proxy itself receives a 401 from discord. Did you try with the `DISABLE_401_LOCK` flag set to `true`? Did that help?
> 
> It's also wierd that your 429 curve is so high on /gateway/bot, are you spamming that endpoint with multiple bots? Are all your workloads going through the proxy? How many bots or applications that communicate with Discord share the same IP?

1. I don't know what flag you are talking about
2. 4 nirn replicas, 3 bots (one with max_concurrency of 16)

**Comment by germanoeich** [comment]
> I don't know what flag you are talking about

There is an environment variable called "DISABLE_401_LOCK", can you set that to true and see if this issue stops happening?

> 4 nirn replicas, 3 bots (one with max_concurrency of 16)

Are *all* the applications proxied?

**Comment by hydrox19** [comment]
> > I don't know what flag you are talking about
> 
> There is an environment variable called "DISABLE_401_LOCK", can you set that to true and see if this issue stops happening?
> 
> > 4 nirn replicas, 3 bots (one with max_concurrency of 16)
> 
> Are _all_ the applications proxied?

Yes

**Comment by germanoeich** [comment]
Please, answer all the questions. It's really difficult to help you if you don't give me context and information.

Have you tried the environment variable? Did it help?

**Comment by hydrox19** [comment]
> Please, answer all the questions. It's really difficult to help you if you don't give me context and information.
> 
> Have you tried the environment variable? Did it help?

Oh sorry for missing that out, no I haven't really tried that. I am not sure should I pipe interactions through or not since a lot of times I get unknown interactions and also 404 on interactions and 401 (idk what causes it).

**Comment by germanoeich** [comment]
We pipe all our requests through nirn, interactions, webhooks, normal requests and we have no issues.

What version are you running? I published a new version that should have fixed the 401 issues with interactions specifically a few days ago.

**Comment by hydrox19** [comment]
> We pipe all our requests through nirn, interactions, webhooks, normal requests and we have no issues.
> 
> What version are you running? I published a new version that should have fixed the 401 issues with interactions specifically a few days ago.

I will try with the flag and get back to you.

**Comment by hydrox19** [comment]
![image](https://user-images.githubusercontent.com/85543339/163657960-740f1d2b-7e75-4409-b118-3ce99eaf0e5e.png)
This is the result after using the flag.

**Comment by hydrox19** [comment]
DELETE /channels/!/messages/! (429 Too Many Requests)
GET /channels/! (429 Too Many Requests)
GET /guilds/!/members/! (429 Too Many Requests)
PATCH /guilds/!/members/! (429 Too Many Requests)
PATCH /webhooks/!/!/messages/@original (429 Too Many Requests)
POST /channels/!/messages (429 Too Many Requests)
POST /interactions/!/!/callback (429 Too Many Requests)
PUT /channels/!/messages/!/reactions/!/! (429 Too Many Requests)

**Comment by germanoeich** [comment]
I am confused, is the issue with 429s or 401s?

A 401 will stop the proxy dead in it's track if it doesn't come from webhooks or interactions. This is expected, and is what the DISABLE_401_LOCK env var prevents.

A 429 is a recoverable request, and will happen during normal proxy usage, although the volume won't be enough to cause issues. 

Per the docs for this project, you are responsible for retrying a 429 if the proxy happens to return one. Discord.js should handle this automatically.

What is the issue here exactly?

**Comment by hydrox19** [comment]
> I am confused, is the issue with 429s or 401s?
> 
> A 401 will stop the proxy dead in it's track if it doesn't come from webhooks or interactions. This is expected, and is what the DISABLE_401_LOCK env var prevents.
> 
> A 429 is a recoverable request, and will happen during normal proxy usage, although the volume won't be enough to cause issues.
> 
> Per the docs for this project, you are responsible for retrying a 429 if the proxy happens to return one. Discord.js should handle this automatically.
> 
> What is the issue here exactly?

My question is why I am getting 429 on interactions, even tho interactions don't have a ratelimit afaik. I know other routes are my issue.

**Comment by germanoeich** [comment]
Well what I can say is that the proxy is not generating those 429s, they are coming from discord directly.

Check if you are calling /callback on multiple places, hook your request to a logger to check the body for those requests, etc and try to check for useful error messages from Discord
